name: Selenium Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Install Chrome, Firefox, and Edge
      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y firefox
          sudo apt-get install -y microsoft-edge-stable

      # Verify browser versions
      - name: Verify browser versions
        run: |
          google-chrome --version
          firefox --version
          microsoft-edge --version

      # Install dependencies and run tests
      - name: Build and Test with Maven
        run: mvn clean install
